<?php if (!isSet(Zend_Auth::getInstance()->getIdentity()->id)) : ?>
<form action="/auth/login" method="POST">
    <label>Username</label><input type="text" name="username" /><br />
    <label>Password</label><input type="text" name="password" />
</form>
<?php endif; ?>
<?php if (isSet(Zend_Auth::getInstance()->getIdentity()->id)) : ?>
You are already logged in. <a href="/auth/logout">Logout</a>
<?php endif; ?>
